### ISSUE TITLE
getPathInput shouldn't call check if the value is not required

### ISSUE THREAD

**Issue by hinzo** [Microsoft/vso-task-lib#2]
If the value is optional. The call to getPathInput ends up calling checkPath on a null value.

**Comment by bryanmacfarlane** [comment]
I think it's doing the right thing.  If check is not supplied, it's null. 
export function getPathInput(name, required, check) {
...

    if (check) {
        checkPath(inval, name);
    }

$ node
> var test = function(test) { if (test) { console.log('do test'); }};
undefined
> test(true)
do test
undefined
> test()
undefined
>

**Comment by hinzo** [comment]
@bryanmacfarlane 

The issue is when required is false (optional) and the value doesn't exist. So, "inval" is null.  In this case checkPath is called on a null value when it shouldn't be called in the first place.

getPathInput("something_not_present", false, true) <-- throws exeption

The code need to look like this:

    if (inval && check) {
        checkPath(inval, name);
    }
