### ISSUE TITLE
minimatch should be runtime dependency

### ISSUE THREAD

**Issue by hinzo** [Microsoft/vso-task-lib#3]
minmatch module is currently set as dev dependency but it's used inside the task lib code. the require need to be removed or the module should be referenced in the dependency section.

**Comment by bryanmacfarlane** [comment]
agreed

**Comment by pascalberger** [comment]
This was fixed by #5

**Comment by kjrb** [comment]
Hi,
Would it be possible to publish the fixed version to npm? I am using vso-task-lib and as a workaround I have to import minmatch in my package to avoid error in vso-task-lib.The npm version does not have minmatch in dependencies.

**Comment by halkeye** [comment]
Seconding the new npm release.
Especially 'cause with the current directory structure, you can't npm install the git branch.

**Comment by bryanmacfarlane** [comment]
published
