### ISSUE TITLE
Updating task lib through vsoagent-installer

### ISSUE THREAD

**Issue by blsmithers** [Microsoft/vso-task-lib#6]
I feel like this is something I'm doing wrong but I can't quite figure this out, apologies. I have updated the vsoagent-installer:

sudo npm install vsoagent-installer -g

and the output indicates vso-task-lib@0.4.5

I then execute vsoagent-installer on my agent which pulls in the new scripts. For vso-task-lib the package.json indicates a version of 0.4.5 but the related change to lib/vsotask.js isn't there. This is consistent with what I'm seeing in /usr/local/lib/node_modules/vsoagent-installer/node_modules/vso-task-lib.

It's weird I'm seeing the 0.4.5 version but not an updated vsotask file, am I missing a step? Thanks in advance.

**Comment by bryanmacfarlane** [comment]
>> but the related change to lib/vsotask.js isn't there

Which specific change are you looking for?  I can investigate

**Comment by blsmithers** [comment]
https://github.com/Microsoft/vso-task-lib/pull/1

**Comment by bryanmacfarlane** [comment]
And you're installing the latest version of the agent?

**Comment by blsmithers** [comment]
Here's the command I used and the output

$ sudo npm install vsoagent-installer -g
npm WARN engine xmlbuilder@2.2.1: wanted: {"node":"0.8.x || 0.10.x"} (current: {"node":"0.12.7","npm":"2.11.3"})
/usr/local/bin/vsoagent-installer -> /usr/local/lib/node_modules/vsoagent-installer/bin/install.js
vsoagent-installer@0.2.29 /usr/local/lib/node_modules/vsoagent-installer
├── iniparser@1.0.5
├── svchost@0.1.2
├── minimist@0.2.0
├── node-uuid@1.4.3
├── validator@3.11.2
├── async@0.9.2
├── q@1.4.1
├── read@1.0.7 (mute-stream@0.0.5)
├── adm-zip@0.4.7
├── shelljs@0.2.6
├── vso-task-lib@0.4.5 (shelljs@0.3.0)
├── glob@5.0.15 (path-is-absolute@1.0.0, inherits@2.0.1, once@1.3.2, inflight@1.0.4)
├── minimatch@2.0.10 (brace-expansion@1.1.1)
├── xmlreader@0.2.3 (sax@0.5.8)
├── nconf@0.6.9 (ini@1.3.4, async@0.2.9, optimist@0.6.0)
└── svcinstall@0.2.1 (shelljs@0.3.0, plist@1.1.0)

**Comment by blsmithers** [comment]
After the update to the agent I'm checking for the change in the file:
/usr/local/lib/node_modules/vsoagent-installer/node_modules/vso-task-lib/lib/vsotask.js

I also run vsoagent-installer on my agent and check file <agent>/node_modules/vso-task-lib/lib/vsotask.js  and it too doesn't show the change

**Comment by blsmithers** [comment]
Bryan do you have an update on this by any chance?

**Comment by blsmithers** [comment]
It still appears the public version of this package at npmjs.org does not have the most recent changes. Should I pull this package from another source?

**Comment by bryanmacfarlane** [comment]
Latest the agent uses (4.8) was publish and has the changes.  5.1 was also published with more changes for a future agent.  If you install a new copy of latest agent (0.3.x) it should have
